### ISSUE TITLE
It makes topic list to the same title as the category name

### ISSUE THREAD

**Issue by tangramor** [yariplus/nodebb-plugin-rainbows#3]
strange ....

![qq 20180329185756](https://user-images.githubusercontent.com/491287/38085478-4751bc78-3383-11e8-9f28-08eb65779cb4.png)

**Comment by tangramor** [comment]
Correct list:
![qq 20180329185935](https://user-images.githubusercontent.com/491287/38085544-7bee7250-3383-11e8-8449-f455b2f6ac59.png)

**Comment by yariplus** [comment]
Turn off "Color Topic Titles", I think that should fix it.

**Comment by tangramor** [comment]
Yes, this workaround works. However, it is still a defect...

**Comment by yariplus** [comment]
fixed in 1.4.1
