### ISSUE TITLE
It has a bug with links

### ISSUE THREAD

**Issue by nidbCN** [yariplus/nodebb-plugin-rainbows#5]
This plugs has a bug when there are links in the words
我英语不是很好，看图
![b1](https://user-images.githubusercontent.com/36162655/41728196-c278c60a-75a8-11e8-8c88-fd0a8cded815.PNG)

**Comment by yariplus** [comment]
Ew yuck, that's going to be a tough one to fix. I'll need to change the regex to something url-safe.

**Comment by nidbCN** [comment]
This is useful,I hope it will be better.Thank you.

**Comment by yariplus** [comment]
Can you try the new version? New format is

```
~[

content

]~(options)
```

**Comment by nidbCN** [comment]
But the auto add format is old
![00](https://user-images.githubusercontent.com/36162655/41820935-01c41674-780c-11e8-97ec-1d1a30ed0478.PNG)
![01](https://user-images.githubusercontent.com/36162655/41820936-01f62772-780c-11e8-9938-bc9a3b70e04d.PNG)
![02](https://user-images.githubusercontent.com/36162655/41820957-441831a4-780c-11e8-90f2-ff994df8c448.PNG)
And are you play Minecraft?

**Comment by yariplus** [comment]
Ah, good point. I will make the GUI use the new format.

and yes, I do.

**Comment by nidbCN** [comment]
Thank you very much.
It is coincidence that my forums (which use rainbow)is a Minecraft forums
http://www.minecrafter.cn/

**Comment by yariplus** [comment]
Awesome!

Pushed an update so the editor uses the new format.
